### PR TITLE
Client transitions still need to render in order

### LINKED ISSUE #961: Navigation playground is broken
Looks like I broke it in https://github.com/redfin/react-server/pull/948.

This likely means client transitions are totally borked right now.

### PR DESCRIPTION
**Pull request by gigabo**
During client transitions the root structure is built up using a state machine that requires an in-order render. First render can still go out of order because the server has already laid out the root structure.

This fixes #961.

### CODE REVIEW

File: packages/react-server/core/ClientController.js [hunk 1]
```diff
@@ -601,26 +601,35 @@ class ClientController extends EventEmitter {
 			}
```
Comment (gigabo) [inline packages/react-server/core/ClientController.js]: May be easier to look at with [whitespace changes hidden](https://github.com/redfin/react-server/pull/962/files?w=1).
